In [3]:
import pandas as pd
# Load dataset
cc_apps = pd.read_csv('datasets/crx.data',header=None)

# Inspect data
cc_apps.head(10)

  0      1       2  3  4   5  6      7  8  9   10 11 12     13     14 15
0  b  30.83   0.000  u  g   w  v  1.250  t  t   1  f  g  00202      0  +
1  a  58.67   4.460  u  g   q  h  3.040  t  t   6  f  g  00043    560  +
2  a  24.50   0.500  u  g   q  h  1.500  t  f   0  f  g  00280    824  +
3  b  27.83   1.540  u  g   w  v  3.750  t  t   5  t  g  00100      3  +
4  b  20.17   5.625  u  g   w  v  1.710  t  f   0  f  s  00120      0  +
5  b  32.08   4.000  u  g   m  v  2.500  t  f   0  t  g  00360      0  +
6  b  33.17   1.040  u  g   r  h  6.500  t  f   0  t  g  00164  31285  +
7  a  22.92  11.585  u  g  cc  v  0.040  t  f   0  f  g  00080   1349  +
8  b  54.42   0.500  y  p   k  h  3.960  t  f   0  f  g  00180    314  +
9  b  42.50   4.915  y  p   w  v  3.165  t  f   0  t  g  00052   1442  +

In [6]:
# Print summary statistics
cc_apps_description = cc_apps.describe()
print(cc_apps_description)

print('\n')

# Print DataFrame information
cc_apps_info = cc_apps.info()
print(cc_apps_info)

print('\n')

# Inspect missing values in the dataset
cc_apps.tail(20)

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       690 non-null    object
 1   1       690 non-null    object
 2   2       690 non-null    float64
 3   3       690 non-null    object
 4   4       690 non-null    object
 5   5       690 non-null    object
 6   6       690 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    int64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      690 non-null    object
 14  14      690 non-null    int64
 15  15      690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB
None

    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670  b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671  b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672  a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [11]:
# Import train_test_split
from sklearn.model_selection import train_test_split
# Drop the features 11 and 13
cc_apps = cc_apps.drop(columns=[11,13])

# Split into train and test sets
cc_apps_train, cc_apps_test = train_test_split(cc_apps, test_size=0.33, random_state=42)
cc_apps_train.head(10)

    0      1      2  3  4   5   6       7  8  9   10 12    14 15
382  a  24.33  2.500  y  p   i  bb   4.500  f  f   0  g   456  -
137  b  33.58  2.750  u  g   m   v   4.250  t  t   6  g     0  +
346  ?  32.25  1.500  u  g   c   v   0.250  f  f   0  g   122  -
326  b  30.17  1.085  y  p   c   v   0.040  f  f   0  g   179  -
33   a  36.75  5.125  u  g   e   v   5.000  t  f   0  g  4000  +
426  a  27.67  2.040  u  g   w   v   0.250  f  f   0  g    50  -
477  b  39.17  2.500  y  p   i   h  10.000  f  f   0  s     0  -
9    b  42.50  4.915  y  p   w   v   3.165  t  f   0  g  1442  +
22   a  47.75  8.000  u  g   c   v   7.875  t  t   6  g  1260  +
300  a  57.58  2.000  u  g  ff  ff   6.500  f  t   1  g    10  -

In [12]:
import numpy as np
# Replace the '?'s with NaN in the train and test sets
cc_apps_train = cc_apps_train.replace('?',np.nan)
cc_apps_test = cc_apps_test.replace('?',np.nan)
cc_apps_test.head(20)

    0      1       2  3  4   5   6      7  8  9   10 12   14 15
286  a    NaN   1.500  u  g  ff  ff  0.000  f  t   2  g  105  -
511  a  46.00   4.000  u  g   j   j  0.000  t  f   0  g  960  +
257  b  20.00   0.000  u  g   d   v  0.500  f  f   0  g    0  -
336  b  47.33   6.500  u  g   c   v  1.000  f  f   0  g  228  -
318  b  19.17   0.000  y  p   m  bb  0.000  f  f   0  s    1  +
211  b  24.33   6.625  y  p   d   v  5.500  t  f   0  s    0  +
624  b  21.58   0.790  y  p  cc   v  0.665  f  f   0  g    0  -
176  b  25.00  12.500  u  g  aa   v  3.000  t  f   0  s    0  +
462  b  21.92   0.500  u  g   c   v  0.125  f  f   0  g    0  -
256  b  20.00  11.045  u  g   c   v  2.000  f  f   0  g    0  -
662  a  23.50   1.500  u  g   w   v  0.875  f  f   0  g    0  -
165  a  40.83  10.000  u  g   q   h  1.750  t  f   0  g  837  +
621  b  22.67   0.165  u  g   c   j  2.250  f  f   0  s    0  +
78   b  21.67   1.165  y  p   k   v  2.500  t  t   1  g   20  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  g    3  -
497  b  20.17   9.250  u  g   c   v  1.665  t  t   3  g   28  +
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  g  537  -
294  a  16.08   0.335  u  g  ff  ff  0.000  f  t   1  g  126  -
645  b  37.33   2.665  u  g  cc   v  0.165  f  f   0  g  501  -
396  b  29.83   2.040  y  p   x   h  0.040  f  f   0  g    1  -

In [13]:
# Impute the missing values with mean imputation
cc_apps_train.fillna(cc_apps_train.mean(), inplace=True)
cc_apps_test.fillna(cc_apps_test.mean(), inplace=True)

# Count the number of NaNs in the datasets and print the counts to verify

cc_apps_train.isnull().sum(),cc_apps_test.isnull().sum()

C:\Users\abelyang\AppData\Local\Temp\ipykernel_932\3636745365.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  cc_apps_train.fillna(cc_apps_train.mean(), inplace=True)
C:\Users\abelyang\AppData\Local\Temp\ipykernel_932\3636745365.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  cc_apps_test.fillna(cc_apps_test.mean(), inplace=True)

(0     8
 1     5
 2     0
 3     6
 4     6
 5     7
 6     7
 7     0
 8     0
 9     0
 10    0
 12    0
 14    0
 15    0
 dtype: int64,
 0     4
 1     7
 2     0
 3     0
 4     0
 5     2
 6     2
 7     0
 8     0
 9     0
 10    0
 12    0
 14    0
 15    0
 dtype: int64)

In [14]:
# Iterate over each column of cc_apps_train
for col in cc_apps_train:
    # Check if the column is of object type
    if cc_apps_train[col].dtypes == 'object':
        # Impute with the most frequent value
        cc_apps_train[col] = cc_apps_train[col].fillna(cc_apps_train[col].value_counts().index[0])
        cc_apps_test[col] = cc_apps_test[col].fillna(cc_apps_test[col].value_counts().index[0])

In [15]:
# Convert the categorical features in the train and test sets independently
cc_apps_train = pd.get_dummies(cc_apps_train)
cc_apps_test = pd.get_dummies(cc_apps_test)

# Reindex the columns of the test set aligning with the train set
cc_apps_test = cc_apps_test.reindex(columns=cc_apps_train.columns, fill_value=0)
cc_apps_train.head(10)

,2,7,10,14,0_a,0_b,1_13.75,1_15.83,1_15.92,1_16.00,...,6_z,8_f,8_t,9_f,9_t,12_g,12_p,12_s,15_+,15_-
382,2.500,4.500,0,456,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
137,2.750,4.250,6,0,0,1,0,0,0,0,...,0,0,1,0,1,1,0,0,1,0
346,1.500,0.250,0,122,0,1,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
326,1.085,0.040,0,179,0,1,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
33,5.125,5.000,0,4000,1,0,0,0,0,0,...,0,0,1,1,0,1,0,0,1,0
426,2.040,0.250,0,50,1,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,1
477,2.500,10.000,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,1,0,1
9,4.915,3.165,0,1442,0,1,0,0,0,0,...,0,0,1,1,0,1,0,0,1,0
22,8.000,7.875,6,1260,1,0,0,0,0,0,...,0,0,1,0,1,1,0,0,1,0
300,2.000,6.500,1,10,1,0,0,0,0,0,...,0,1,0,0,1,1,0,0,0,1

In [16]:
# Import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler 
# Segregate features and labels into separate variables
X_train, y_train = cc_apps_train.iloc[:,0:-2].values, cc_apps_train.iloc[:,-2].values
X_test, y_test = cc_apps_test.iloc[:,0:-2].values, cc_apps_test.iloc[:,-2].values

# Instantiate MinMaxScaler and use it to rescale X_train and X_test
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.transform(X_test)

In [17]:
y_train[:10]

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0], dtype=uint8)

In [18]:
# Import LogisticRegression

from sklearn.linear_model import LogisticRegression

# Instantiate a LogisticRegression classifier with default parameter values
logreg = LogisticRegression()


# Fit logreg to the train set
logreg.fit(rescaledX_train, y_train)

LogisticRegression()

In [19]:
# Import confusion_matrix

from sklearn.metrics import confusion_matrix 
# Use logreg to predict instances from the test set and store it
y_pred = logreg.predict(rescaledX_test)

# Get the accuracy score of logreg model and print it
print("Accuracy of logistic regression classifier: ", logreg.score(rescaledX_test,y_test))

# Print the confusion matrix of the logreg model
confusion_matrix(y_test,y_pred)

Accuracy of logistic regression classifier:  0.8421052631578947

array([[98, 27],
       [ 9, 94]], dtype=int64)

In [20]:
# Import GridSearchCV

from sklearn.model_selection import GridSearchCV 
# Define the grid of values for tol and max_iter
tol = [0.01,0.001,0.0001]
max_iter = [100,150,200]

# Create a dictionary where tol and max_iter are keys and the lists of their values are corresponding values
param_grid = dict(tol=tol, max_iter=max_iter)

In [21]:
# Instantiate GridSearchCV with the required parameters
grid_model = GridSearchCV(estimator=logreg, param_grid=param_grid, cv=5)

# Fit grid_model to the data
grid_model_result = grid_model.fit(rescaledX_train,y_train)

# Summarize results
best_score, best_params = grid_model_result.best_score_, grid_model_result.best_params_
print("Best: %f using %s" % (best_score,best_params))

# Extract the best model and evaluate it on the test set
best_model = grid_model_result.best_estimator_
print("Accuracy of logistic regression classifier: ", best_model.score(rescaledX_test,y_test))

Best: 0.867906 using {'max_iter': 100, 'tol': 0.01}
Accuracy of logistic regression classifier:  0.8421052631578947